% Unit-test for dh2jacobian function

clear;
clc;

table = [   sym('[L1,pi/2,  0,  q1(t)]'); ...
            sym('[L2,   0,  0,  q2(t)]'); ...
            sym('[L3,   0,  0,  q3(t)]'); ...
            sym('[L4,   0,  0,  q4(t)]')  ...
        ];

[J,H,A] = dh2jacobian(table,'RRRR');
